title: Lewis | Industrial Engineer & Computer Scientist
description: Dual Master's in Industrial Engineering & Computer Science | Optimization, Data, Automation
theme: jekyll-theme-minimal
show_downloads: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
